name: List S3 Files

on: [ push ]

jobs:
  list-s3-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List S3 files
        run: |
          aws s3 ls ${{ secrets.AWS_BUCKET }}/reports/ --recursive > s3-file-list.txt

      - name: Upload S3 file list artifact
        uses: actions/upload-artifact@v3
        with:
          name: s3-file-list
          path: s3-file-list.txt

  commit-file:
    runs-on: ubuntu-latest
    needs: list-s3-files

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download S3 file list artifact
        uses: actions/download-artifact@v3
        with:
          name: s3-file-list
          path: .

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add s3-file-list.txt
          git commit -m 'Add S3 file list'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}